### ISSUE TITLE
[new tools] -- thingsboard-sandbox

### ISSUE THREAD

**Issue by a631953720** [devaskim/awesome-thingsboard#2]
Hi, I create a new project [thingsboard-sandbox](https://github.com/a631953720/thingsboard-sandbox)

This project provides a simple service

After creating the webhook between the thingsboard-sandbox and thingsboard rule chain

This sandbox can handle receiving data

For more information, you can access my [thingsboard-sandbox](https://github.com/a631953720/thingsboard-sandbox)

The document has recorded how to create a webhook  between the thingsboard-sandbox and thingsboard rule chain

Thanks

**Comment by devaskim** [comment]
Thanks @a631953720. Added your project to the [Tools section](https://github.com/devaskim/awesome-thingsboard/blob/main/README.md#tools)
