### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by Raven888888** [devaskim/awesome-thingsboard#3]
Thanks author for keeping a curated list of cool projects related to Thingsboard, this repo should really be endorsed officially by Thingsboard!

Kudos!

**Comment by devaskim** [comment]
Thanks @Raven888888 It is important for me

Unfortunately, I expected that TB community will be more interested in contributing. 

As for me last few month till now I am focusing on contributing in [thingsboard](https://github.com/thingsboard/thingsboard/pulls?q=is%3Apr+author%3Adevaskim+) and [thingsboard-gateway](https://github.com/thingsboard/thingsboard-gateway/pulls?q=is%3Apr+author%3Adevaskim+) projects. And I already have a lot of interesting widgets and rule chain solutions but all of this requires time to preparing it for sharing with community. 

So stay tuned!
