### ISSUE TITLE
Tenant migration

### ISSUE THREAD

**Issue by mircopz** [devaskim/awesome-thingsboard#4]
Hello, nice project! I've only just discovered this repository, but I've seen that you have so many useful features.
Just a question (or a suggestion): there is already a procedure, in the migration scripts, to export dashboards, rule engine and some entities, from a thingsboard instance to another? In order to simplify the deploy of a new tenant. I think the most complex part is the rule chains with their relations

**Comment by devaskim** [comment]
It is not ideal, but Thingsboard provides feature called [Version Control](https://thingsboard.io/docs/user-guide/version-control/). Did you try it?

**Comment by t0mZ4** [comment]
i think you should open a feature request on thingsboard to address this.
They should have a centralized management for rule chains/dashboards across
tenants :)

**Comment by mircopz** [comment]
Yes you are right, I know this feature on thingsboard 3.x, but I need this on an old thingsboard instance based on 2.5.
Thank you anyway!
